### ISSUE TITLE
use logging.yml file to set plugin log level

### ISSUE THREAD

**Issue by bhurlow** [rethinkdb/elasticsearch-river-rethinkdb#10]
Not sure if this is the right place to put this issue. 

I need to suppress the `DEBUG` logs caused by `com.rethinkdb.RethinkDBConnection` package. It's not clear to me if the vendor rethinkdb client follows the elasticsearch [logging conventions](https://github.com/docker-library/elasticsearch/blob/c0cc86cddec0de3bd8fa01bcca5ef0c36fc7d255/1.7/config/logging.yml)

Thanks!

**Comment by danielmewes** [comment]
The river plugin is built on top of an inofficial Java driver for RethinkDB contributed by @npiv, which is no longer maintained (https://github.com/npiv/rethink-java-driver).

You might want to try the RethinkDB logstash input instead https://github.com/rethinkdb/logstash-input-rethinkdb which is going to replace the River plugin soon.

**Comment by bhurlow** [comment]
thnx!

**Comment by deontologician** [comment]
closing since this repo is no longer maintained
