### ISSUE TITLE
ES 1.4.x support

### ISSUE THREAD

**Issue by frankleng** [rethinkdb/elasticsearch-river-rethinkdb#6]
Just wondering if 1.4 .x support is on the roadmap

**Comment by yaru22** [comment]
+1 to 1.4.x support

**Comment by pilwon** [comment]
:+1: x 100

**Comment by deontologician** [comment]
I really want to do this, but crunched at the moment. Patches are really welcome though until I can get to it

**Comment by vierja** [comment]
It's working for me with 1.4.2.

**Comment by scripter-co** [comment]
+1

**Comment by frankleng** [comment]
@vierja is right. not sure why it didn't work for me the first time. 
confirmed working on ES 1.4.4 as well.

**Comment by pilwon** [comment]
@frankleng Could we update README to indicate it supports 1.4? Thanks-

**Comment by danielmewes** [comment]
@deontologician ^^^^^

**Comment by vierja** [comment]
Also a deprecation warning since rivers are deprecated in 1.5 and are going to be removed in the future, and I am not sure the new logstash solution is going to live in this repo.

**Comment by deontologician** [comment]
I'll add the version mention in the README. I'll leave the deprecation warning until we have a the logstash input finished (which I am working on now). There's nothing more frustrating than being told something is deprecated but there's no replacement.
