### ISSUE TITLE
does this incorporate the rethinkDB changefeed for near-realtime ingestion?

### ISSUE THREAD

**Issue by gebrits** [rethinkdb/elasticsearch-river-rethinkdb#8]
When glancing the docs it seems I need to manually start (re)indexing of an ES index based on RethinkDB-table. Is that correct? 

For occasional full re-indexing this is prefect. However, it would be great to be able to hook the ES-river into the RethinkDB-changefeed for near-realtime updating/syncing ES with RethinkDB. I'm sure this is not a novel idea :), but is are there any thoughts / progress done in this direction?

**Comment by deontologician** [comment]
Yeah, this uses changefeeds underneath. It does an initial ingestion (if you set that option), and then it sets up a changefeed listening for updates to the tables you've configured it to watch.

**Comment by gebrits** [comment]
Awesome.
